---
- name: Set http::Proxy in /etc/apt/apt.conf.d/70proxy to {{ set_http_proxy_apt_config_state }}
  become: yes
  become_user: root
  lineinfile:
    path: /etc/apt/apt.conf.d/70proxy
    create: yes
    state: "{{ set_http_proxy_apt_config_state }}"
    regexp: '^Acquire::http::Proxy '
    line: 'Acquire::http::Proxy "{{ set_http_proxy_apt_config_http_proxy }}";'

- name: Set https::Proxy in /etc/apt/apt.conf.d/70proxy to {{ set_http_proxy_apt_config_state }}
  become: yes
  become_user: root
  lineinfile:
    path: /etc/apt/apt.conf.d/70proxy
    create: yes
    state: "{{ set_http_proxy_apt_config_state }}"
    regexp: '^Acquire::https::Proxy '
    line: 'Acquire::https::Proxy "{{ set_http_proxy_apt_config_https_proxy }}";'