---
- name: template k8s manifests for serviceaccounts csi-cluster-admin and csi-cluster-reporter
  template:
    src: ./templates/serviceaccounts.yaml.j2
    dest: "{{k8s_bootstrap_dir}}/serviceaccounts.yaml"

- name: create serviceaccounts csi-cluster-admin and csi-cluster-reporter
  shell: "kubectl --kubeconfig {{kubeconfig}} apply -f {{k8s_bootstrap_dir}}/serviceaccounts.yaml"
  changed_when: ('created' in kubectl_result.stdout) or
                ('configured' in kubectl_result.stdout)