---
- name: template k8s manifests for clusterroles csi-cluster-admin and csi-cluster-reporter
  template:
    src: ./templates/clusterroles.yaml.j2
    dest: "{{k8s_bootstrap_dir}}/clusterroles.yaml"

- name: create clusterroles csi-cluster-admin and csi-cluster-reporter
  shell: "kubectl --kubeconfig {{kubeconfig}} apply -f {{k8s_bootstrap_dir}}/clusterroles.yaml"
  changed_when: ('created' in kubectl_result.stdout) or
                ('configured' in kubectl_result.stdout)