---
- name: template k8s manifests for clusterrolebindings csi-cluster-admin and csi-cluster-reporter
  template:
    src: ./templates/clusterrolebindings.yaml.j2
    dest: "{{k8s_bootstrap_dir}}/clusterrolebindings.yaml"

- name: create clusterrolebindings csi-cluster-admin and csi-cluster-reporter
  shell: "kubectl --kubeconfig {{kubeconfig}} apply -f {{k8s_bootstrap_dir}}/clusterrolebindings.yaml"
  changed_when: ('created' in kubectl_result.stdout) or
                ('configured' in kubectl_result.stdout)