---
#Default proxy settings will be obtained from the http_proxy and https_proxy variables in the inventory
#/etc/environment
##should /etc/environment be modified or should it be kept as is?
set_http_proxy_etc_environment_modify: false
##should the given proxy settings be present or absent (added/deleted) in /etc/environment after running the role
set_http_proxy_etc_environment_state: "present"
set_http_proxy_etc_environment_HTTP_PROXY: "{{set_http_proxy_http_proxy}}"
set_http_proxy_etc_environment_HTTPS_PROXY: "{{set_http_proxy_https_proxy}}"
set_http_proxy_etc_environment_http_proxy: "{{set_http_proxy_http_proxy}}"
set_http_proxy_etc_environment_https_proxy: "{{set_http_proxy_https_proxy}}"

##apt
##should /etc/apt/apt.conf.d/70proxy be modified or should it be kept as is?
set_http_proxy_apt_config_modify: false
##should the given proxy settings be present or absent (added/deleted) in /etc/apt/apt.conf.d/70proxy after running the role
set_http_proxy_apt_config_state: "present"
set_http_proxy_apt_config_http_proxy: "{{set_http_proxy_http_proxy}}"
set_http_proxy_apt_config_https_proxy: "{{set_http_proxy_https_proxy}}"

##apt
##should /etc/apt/apt.conf.d/70proxy be modified or should it be kept as is?
set_http_proxy_yum_config_modify: false
##should the given proxy settings be present or absent (added/deleted) in /etc/apt/apt.conf.d/70proxy after running the role
set_http_proxy_yum_config_state: "present"
set_http_proxy_yum_config_http_proxy: "{{set_http_proxy_http_proxy}}"

##~/set_http_proxy_profile
##should ~/.profile be modified or should it be kept as is?
set_http_proxy_profile_modify: false
##should the given proxy settings be present or absent (added/deleted) in ~/.profile after running the role
set_http_proxy_profile_state: "present"
##the user whose .profile should be modified
set_http_proxy_profile_user: "root"
set_http_proxy_profile_HTTP_PROXY: "{{set_http_proxy_http_proxy}}"
set_http_proxy_profile_HTTPS_PROXY: "{{set_http_proxy_http_proxy}}"
set_http_proxy_profile_http_proxy: "{{set_http_proxy_http_proxy}}"
set_http_proxy_profile_https_proxy: "{{set_http_proxy_http_proxy}}"

## set /etc/wgetrc proxy
set_http_proxy_wget_modify: false
set_http_proxy_wget_state: "present"
set_http_proxy_wget_http_proxy: "{{set_http_proxy_http_proxy}}"
set_http_proxy_wget_https_proxy: "{{set_http_proxy_https_proxy}}"