---
- import_tasks: ubuntu1804/main.yaml
  when:
    - ( ansible_distribution == "Ubuntu" )
    - ( ansible_distribution_version == "18.04" )

- import_tasks: centos7/main.yaml
  when:
    - ( ansible_distribution == 'CentOS')
    - ( ansible_distribution_version == '7' )

- name: template and overwrite /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf


- name: restart and enable ntpd
  service:
    name: ntpd
    state: restarted
    enabled: true
  when:
    - ( ansible_distribution == 'CentOS')
    - ( ansible_distribution_version == '7' )

- name: restart and enable ntp
  service:
    name: ntp
    state: restarted
    enabled: true
  when:
    - ( ansible_distribution == "Ubuntu" )
    - ( ansible_distribution_version == "18.04" )