---
- import_tasks: disable-swap.yaml
  when:
    - ( configure_swap | bool )
    - ( configure_swap_state == 'absent' )

- import_tasks: reenable-swap.yaml
  when:
    - ( configure_swap | bool )
    - ( configure_swap_state == 'present' )