---
galaxy_info:
  author: Kevin Sandermann

dependencies:
  - role: configure-installed-packages
    os_install_packages_group_repository_packagelist: []
    os_install_packages_host_repository_packagelist:
      - name: cloud-utils-growpart
        version: "*"
    when:
      - ansible_distribution == 'CentOS'
      - ansible_distribution_version == '7'