---
#### for exemplary vars, see /tests/playbook.yaml
### vsphere config
#vsphere_management_vcenter_ip: "193.29.131.112"
#vsphere_management_vcenter_port: 50187
#vsphere_management_user: "nit.de\\srv-vcs-ats"
##vsphere_management_password: vmware --> set when running the playbook, i.e. -e vsphere_management_password=password123
vsphere_validate_certs: no
#vsphere_datacenter: "CGI-DC"
#vsphere_cluster: "CL_SHARED-Std"
#vsphere_resource_pool: "ATS-Automation"
#vsphere_folder: "/CL_SHARED-Std/ATS-Automation"

##vm config
#vsphere_vm_state: "poweredon" ## poweredon/poweredoff
##vsphere_vm_name: -> set as variable in the playbook
#vsphere_vm_cpus: 4
#vsphere_vm_memory: 8192
#vsphere_template_name: "ubuntu1604.template"

##vm networking config
#vsphere_vm_network_vlan_id: 199
#vsphere_vm_network_type: static
#vsphere_vm_network_ip: 193.29.130.74
#vsphere_vm_network_netmask: 255.255.255.0
#vsphere_vm_network_gateway: 193.29.130.1
#vsphere_vm_network_dns_servers:
#- 193.29.131.29
#- 193.29.131.37
vsphere_vm_wait_for_ip: yes

##vm custom config
#vsphere_vm_custom_autologon: yes
#vsphere_vm_custom_hostname: k8s-dev-master1

vsphere_vm_provisioning_state: present #present, absent, keep